public class Calculator {

    public static void main(String[] args) {
        //TODO  +, -, *, /, ^, % ;
        
        int firstNumber = 3;
        int secondNumber = 4;
        char mathOperation '+';

        if (mathOperation == '+') {
            System.out.println(firstNumber + secondNumber);
        } else if (mathOperation == '-') {
            System.out.println(firstNumber - secondNumber);
        } else if (mathOperation == '*') {
            System.out.println (firstNumber * secondNumber);
        } else if (mathOperation == '/') {
            System.out.println(firstNumber / secondNumber);
        } else if (mathOperation == '^'){
            System.out.println(firstNumber ^ secondNumber);
            if (secondNumber = 0) {
                System.out.println (1);
            }
            if result = 1
            for (int i = 0; i = secondNumber; i++);
            result = result + secondNumber;
            System.out.println(result);

        }else if (mathOperation == '%') {
            System.out.println(firstNumber % secondNumber);
        }
    }
}
